name: Build and Test
 
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  test:
    strategy:
      matrix:
        node-version: [20.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
        
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: |
            - recursive: false
              args: [--no-frozen-lockfile, --strict-peer-dependencies]
          package_json_file: example/package.json

      - name: Build
        run: pnpm build
